[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.11"
utils = { path = "../utils" }
bitfields = "0.12.4"

[lib]
doctest = false #doc test for thiserror are acting up 2/23/2024
